# Generated by Django 3.1.4 on 2020-12-10 03:59

import django.core.validators
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate', models.DateField(auto_now_add=True, verbose_name='crate')),
                ('update', models.DateField(auto_now=True, verbose_name='update')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('institution', models.CharField(max_length=100, verbose_name='Institution')),
                ('start', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(9999)], verbose_name='Start')),
                ('end', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(9999)], verbose_name='End')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate', models.DateField(auto_now_add=True, verbose_name='crate')),
                ('update', models.DateField(auto_now=True, verbose_name='update')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('functions', models.CharField(max_length=150, verbose_name='Functions')),
                ('phone', models.CharField(max_length=17, verbose_name='Phone')),
                ('about', models.TextField(max_length=1000, verbose_name='About')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('image', stdimage.models.StdImageField(upload_to='<built-in function id>', verbose_name='Image')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('youtube', models.CharField(default='#', max_length=100, verbose_name='Youtube')),
                ('github', models.CharField(default='#', max_length=100, verbose_name='Github')),
                ('linkedin', models.CharField(default='#', max_length=100, verbose_name='Linkedin')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='ExtraEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate', models.DateField(auto_now_add=True, verbose_name='crate')),
                ('update', models.DateField(auto_now=True, verbose_name='update')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Extra Education',
                'verbose_name_plural': 'Extra Educations',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate', models.DateField(auto_now_add=True, verbose_name='crate')),
                ('update', models.DateField(auto_now=True, verbose_name='update')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('progress', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Progess')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
