# Generated by Django 3.1.4 on 2020-12-10 17:30

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.CharField(default=1, max_length=1000, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Image'),
        ),
    ]
