# Generated by Django 3.1.4 on 2020-12-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201210_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='extraeducation',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='description'),
        ),
    ]
